# Task, future, coroutine, callback

### Task

Задачи используются для планирования конкурентного выполнения корутин. Когда корутину оборачивают 
в объект Task, пользуясь функцией наподобие asyncio.create_task(), выполнение корутины автоматически 
планируется на ближайшее время.

Определение может запутать. Понять суть можно из примеров ниже. 

Пусть стоит задача проверить доступность ссылок. Вот как бы это выглядело без использования задач.

```python
import asyncio
import time
from datetime import datetime


async def check_availability(url):
    print(f"Проверяем доступность {url}. Дата и время начала: {datetime.now()}")
    await asyncio.sleep(1)  # имитация http-запроса


async def main():
    urls = [
        "https://yandex.ru",
        "https://google.com",
        "https://wwww.baidu.com",
    ]

    for url in urls:
        await check_availability(url)


start = time.time()

asyncio.run(main())

print("Проверка заняла", round(time.time() - start, 1), "секунд")
```

Вывод:

```text
Проверяем доступность https://yandex.ru. Дата и время начала: 2024-01-16 13:19:46.952830
Проверяем доступность https://google.com. Дата и время начала: 2024-01-16 13:19:47.957817
Проверяем доступность https://wwww.baidu.com. Дата и время начала: 2024-01-16 13:19:48.961647
Проверка заняла 3.0 секунды
```

Код выполнялся 3 секунды, то есть перед тем как запускалась следующая проверка, должна быть
завершена предыдущая. Асинхронность здесь не сработала как ожидалось.

Та же самая задача, но с использованием задач:

```python
import asyncio
import time
from datetime import datetime


async def check_availability(url):
    print(f"Проверяем доступность {url}. Дата и время начала: {datetime.now()}")
    await asyncio.sleep(1)  # имитация http-запроса


async def main():
    task1 = asyncio.create_task(check_availability("https://yandex.ru"))
    task2 = asyncio.create_task(check_availability("https://google.com"))
    task3 = asyncio.create_task(check_availability("https://wwww.baidu.com"))

    await task1
    await task2
    await task3


start = time.time()

asyncio.run(main())

print("Проверка заняла", round(time.time() - start, 1), "секунд")
```

Вывод:

```text
Проверяем доступность https://yandex.ru. Дата и время начала: 2024-01-16 13:27:03.841605
Проверяем доступность https://google.com. Дата и время начала: 2024-01-16 13:27:03.841682
Проверяем доступность https://wwww.baidu.com. Дата и время начала: 2024-01-16 13:27:03.841705
Проверка заняла 1.0 секунду
```

Можно видеть, что корутины были запущены практически в один и тот же момент времени. И, как ожидалось,
были выполнены (условно) параллельно. 

Вариант выше хоть и рабочий, но слегка неудобный - урлов может быть произвольное количество. 
Удобнее написать следующим образом:

```python
import asyncio
import time
from datetime import datetime


async def check_availability(url):
    print(f"Проверяем доступность {url}. Дата и время начала: {datetime.now()}")
    await asyncio.sleep(1)  # имитация http-запроса


async def main():
    urls = [
        "https://yandex.ru",
        "https://google.com",
        "https://wwww.baidu.com",
    ]

    tasks = [asyncio.create_task(check_availability(url)) for url in urls]

    await asyncio.gather(*tasks)


start = time.time()

asyncio.run(main())

print("Проверка заняла", round(time.time() - start, 1), "секунд")
```

Вывод:

```text
Проверяем доступность https://yandex.ru. Дата и время начала: 2024-01-16 13:31:01.333265
Проверяем доступность https://google.com. Дата и время начала: 2024-01-16 13:31:01.333396
Проверяем доступность https://wwww.baidu.com. Дата и время начала: 2024-01-16 13:31:01.333418
Проверка заняла 1.0 секунду
```

### Future

Класс `asyncio.Future()` представляет собой конечный результат асинхронной операции. 
Относится к низко-уровневому API.

Обычно, объекты Future используются для того, чтобы код, основанный на обратном вызове низкого 
уровня мог взаимодействовать с кодом высокого уровня, основанного на синтаксисе async/await. 

Рекомендуемый способ создания объекта Future:

```python
loop.create_future()
```

Ниже пример демонстрирующий установку значения в объект Future:

```python
import asyncio


async def set_after(fut, delay, value):
    await asyncio.sleep(delay)
    fut.set_result(value)


async def main():
    loop = asyncio.get_running_loop()
    fut = loop.create_future()
    loop.create_task(set_after(fut, 1, '... world'))
    print('hello ...')
    print(await fut)


asyncio.run(main())
```
 
Вывод:

```text
hello ...
... world
```

Таска была выполнена спустя одну секунду после того, как была запланирована. Пока длилась секунда ожидания, 
на консоль была выведена строка `hello...`, а `fut` была поставлена на await. Как только в `fut` было установлено
значение `value`, функция `main()` продолжила свою работу и завершилась.

### Coroutine

Корутина - результат вызова асинхронной функции.

```python
import asyncio


async def main():
    print('hello')
    await asyncio.sleep(1)
    print('world')


print(type(main()))
```

Вывод:

```text
<class 'coroutine'>
```

Корутина - это `await`-able объект. Чтобы запустить выполнение кода внутри корутины,
необходимо выполнить `await`.
